[tokens]
bot = ''
evi = '' # this is testing bot

[databases]
psql = ''
testing_psql = ''

redis_dns = ''
testing_redis_dns = ''

[webhooks]
error_logs = ''
join_logs = ''
avatar-status = ''

[avatar_webhooks]
avatars-1 = ''
avatars-2 = ''
avatars-3 = ''
avatars-4 = ''
avatars-5 = ''
avatars-6 = ''
avatars-7 = ''
avatars-8 = ''
avatars-9 = ''
avatars-10 = ''
avatars-11 = ''
avatars-12 = ''
avatars-13 = ''
avatars-14 = ''
avatars-15 = ''

[image_webhooks]
misc-1 = ''
misc-2 = ''
misc-3 = ''
misc-4 = ''
misc-5 = ''
misc-6 = ''
misc-7 = ''
misc-8 = ''
misc-9 = ''
misc-10 = ''

[icon-webhooks]
icons-1 = ''
icons-2 = ''
icons-3 = ''
icons-4 = ''
icons-5 = ''
icons-6 = ''
icons-7 = ''
icons-8 = ''
icons-9 = ''
icons-10 = ''

[keys]
lastfm-key = ''
lastfm-secret = ''
tenor = ''
openai = ''
osu-id = ''
osu-secret = ''
osu-callback = ''
steam-key = ''
genshin-ltoken = ''
genshin-ltuid = ''
dagpi = ''
google-search = ''
google-id = ''
spotify-id = ''
spotify-secret = ''

[twitter]
bearer = ''
key = ''
secret = ''

access_token = ''
access_secret = ''

client_id = ''
client_secret = ''